document.write(100*2+3 + "<br>")
document.write(100/50-50 + "<br>")
document.write(true || false )
document.write("<br>")
document.write(false && false || true || false )
document.write("<br>")
document.write(200/false || true )
document.write("<br>")
document.write("Hamburg" == "Hamburg" )
document.write("<br>")
document.write(7 < 5 * (true && true) + true )
document.write("<br>")
document.write(20 % 6 )
document.write("<br>")
document.write((20 % 3) % 2 )